### ISSUE TITLE
🚀 Enhancement:  Center the content in the footer

### ISSUE THREAD

**Issue by MohcineDev** [appwrite/website#1505]
### 🔖 Enhancement description

I noticed that the content in the footer on mobile devices, including the social media links and the privacy/cookie policy links, is not centered.

### 🎤 Pitch

It would improve the layout and make the design more aesthetically pleasing if these items could be centered in the footer.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ms-Kulkarni** [comment]
Can i work on his issue ?

**Comment by AdityaSrivastava185** [comment]
Hello @MohcineDev , I want to work on this issue , can you please assign this issue to me ??

**Comment by MohcineDev** [comment]
Hi @AdityaSrivastava185 
Unfortunately, I'm not the owner or maintainer of the repository, so I don't have the ability to assign issues.

**Comment by AdityaSrivastava185** [comment]
Ohk , thank you 😊

**Comment by AdityaSrivastava185** [comment]
Hello , I am having an issue setting and running up the project , please help me with that 
I just clone the project , then ran ` npm install` command and then ran `npm run dev` command and then it is showing this error 

`TypeError: Cannot read properties of undefined (reading 'replace')
    at Client.setEndpoint (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/@appwrite.io/console/dist/esm/sdk.js:449:93)
    at C:\Users\HP\OneDrive\Desktop\appwrite-project\website\src\lib\utils\console.ts:9:8
    at async instantiateModule (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)
TypeError: Cannot read properties of undefined (reading 'replace')
    at Client.setEndpoint (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/@appwrite.io/console/dist/esm/sdk.js:449:93)
    at C:\Users\HP\OneDrive\Desktop\appwrite-project\website\src\lib\utils\console.ts:9:8
    at async instantiateModule (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)`

**Comment by ItzNotABug** [comment]
@MohcineDev 
> I noticed that the content in the footer on mobile devices, including the social media links and the privacy/cookie policy links, is not centered.

Its as per our internal designs on website. Thanks.

<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/601a5e68-5f7f-4302-9914-0a598fcb4d92" />

**Comment by ItzNotABug** [comment]
> Hello , I am having an issue setting and running up the project , please help me with that I just clone the project , then ran ` npm install` command and then ran `npm run dev` command and then it is showing this error
> 
> `TypeError: Cannot read properties of undefined (reading 'replace') at Client.setEndpoint (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/@appwrite.io/console/dist/esm/sdk.js:449:93) at C:\Users\HP\OneDrive\Desktop\appwrite-project\website\src\lib\utils\console.ts:9:8 at async instantiateModule (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5) TypeError: Cannot read properties of undefined (reading 'replace') at Client.setEndpoint (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/@appwrite.io/console/dist/esm/sdk.js:449:93) at C:\Users\HP\OneDrive\Desktop\appwrite-project\website\src\lib\utils\console.ts:9:8 at async instantiateModule (file:///C:/Users/HP/OneDrive/Desktop/appwrite-project/website/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)`

If this comes up right after the `npm run dev`, its a know issue and is not an error.
You can safely ignore it as its more of a parsing issue with `Vite`. There's an open PR here - https://github.com/appwrite/website/pull/1693
